format_version: !!int 1

project:
    type: !!str "package"
    github: !!str "https://github.com/Isle-0-Skye/minecraft_pack_manager"

    name: !!str "minecraft_pack_manager"
    display_name: !!str "Minecraft Pack Manager"

    description: !!str "Basic interface to help manage and share minecraft instances"
    help_text: !!str

    version:
        full: !!str "1.0.0"
        released: !!str "2025-06-22"
        name: !!str "We are number one"

        major: !!int 1
        minor: !!int 0
        revision: !!int 0

    languages: ["English"]

setup:
    requires:
        dependencies: {"system": "python3"}
        recommends: {}
        suggests: {}

language:
    name: !!str "python"

    version:
        full: !!str "3.12.3"

        major: !!int 3
        minor: !!int 12
        revision: !!int 3

        known_supported: [
            "3.12.3", 
            "3.12.2", 
            "3.12.1", 
            "3.12.0"
        ]

platform:
    Windows:
        icon: !!str "minecraft.svg"
        category: !!str 
        keywords: []
        runtime_args: []

        known_supported: !!bool true
        version:
            known_supported: [
                "11",
                "10"
            ]
            known_unsupported: []

    Linux:
        icon: !!str "minecraft.svg"
        category: !!str "Game"
        keywords: [
            "games",
            "minecraft"
        ]
        runtime_args: []

        known_supported: !!bool true
        version:
            known_supported: [
                "6.11.0-26-generic"
            ]
            known_unsupported: []

    Darwin:
        icon: !!str 
        category: !!str 
        keywords: []
        runtime_args: []

        known_supported: !!bool false
        version:
            known_supported: []
            known_unsupported: []
