# \/\/\/\/\/ HELP HERE \/\/\/\/\/ #

# lines that begin with a # is a comment or note
# you can add as many comments as you wish they are not read by the app

# everything is seperated into keys and values that is written like below
# key: value
# all values should be put in quotes e.g. "my_value" not my_value
# a valid value is the filename of an image inside the resources image folder

# if a key has no value e.g. " home_page: " it is a header
# each page is seperated by these headers

# /\/\/\/\/\ HELP HERE /\/\/\/\/\ #

general:
    icon: "mpm.png"
    background: "background.png"

home_page:
    upload_button: "upload.png"
    download_button: "download.png"
    settings_button: "settings.png"
    help_button: "help.png"
    play_button: "mojang.png"
    quit_button: "exit.png"

settings_page:
    valid: "online.png"
    invalid: "offline.png"

play_page:
    plus_slash_minus: "plus_slash_minus.png"
    online_icon: "online.png"
    offline_icon: "offline.png"
    unknown_icon: "unknown.png"
